name: system tests with matlab

# Uses the cron schedule for github actions
#
# https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events
#
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

on:

  push:
    branches:
      - main
      - dev
    paths:
      - '**.m'
      - '.github/workflows/*system*'
  pull_request:
    branches:
      - main
    paths:
      - '**.m'
      - '.github/workflows/*system*'
  schedule:
    - cron: "0 0 1,15 * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  system_tests_matlab:

    # only trigger update on upstream repo
    if: github.repository_owner == 'cpp-lln-lab'

    runs-on: ubuntu-20.04

    strategy:
      matrix:
        script: [moae, facerep, fmriprep]
      fail-fast: false

    steps:
      - name: Install datalad
        run: |
          sudo apt-get -y -qq update
          sudo apt-get -y install datalad

      - name: Info
        run: |          
          datalad --version

      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1.0.1
        with:
          # MATLAB release to set up R2020a
          release: R2020a

      - name: Clone cpp_spm
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 2

      - name: Get MoAE fmriprep data
        run: |          
          cd demos/MoAE
          	datalad install --source https://gin.g-node.org/SPM_datasets/spm_moae_fmriprep.git \
					                  inputs/fmriprep  
            cd inputs/fmriprep && datalad get *.json \
                              */*/*tsv \
                              */*/*json \
                              */*/*desc-preproc*.nii.gz \
                              */*/*desc-brain*.nii.gz                                     

      - name: Install SPM
        run: |
          git clone https://github.com/spm/spm12.git --depth 1

      - name: Copy Macs toolbox to SPM inputs_folder
        run: cp -rv lib/MACS spm12/toolbox/MACS

      - name: Run ${{ matrix.script }}
        uses: matlab-actions/run-command@v1.0.1
        with:
          command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run system_tests_${{ matrix.script }};
