name: tests and coverage with matlab

on:

  push:
    branches:
      - main
      - dev
  pull_request:
    branches: ["*"]

  # to trigger update manually from the Action tab in github
  workflow_dispatch:
    inputs:
      log:
        description: "run tests manually"
        required: false

jobs:

  tests_matlab:

    runs-on: ubuntu-22.04

    steps:
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v1.2.2
        with:
          # MATLAB release to set up R2020a
          release: R2020a

      - name: Clone bidspm
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Install SPM
        run: |
          git clone https://github.com/spm/spm12.git --depth 1

      - name: Install Moxunit and MOcov
        run: |
          git clone https://github.com/MOxUnit/MOxUnit.git --depth 1
          git clone https://github.com/MOcov/MOcov.git --depth 1


      - name: Copy Macs toolbox to SPM inputs_folder
        run: cp -rv lib/MACS spm12/toolbox/MACS

      - name: Prepare data
        run: |
          cd tests
          make data

      - name: Run commands
        uses: matlab-actions/run-command@v1.1.1
        with:
          command: cd(fullfile(getenv('GITHUB_WORKSPACE'), '.github', 'workflows')); run tests_matlab;

      - name: Check tests
        run: |
          cat test_report.log | grep 0

      - name: Code coverage
        uses: codecov/codecov-action@v3
        with:
          file: coverage.xml
          flags: matlab
          name: codecov-matlab
          fail_ci_if_error: false
        # token: ${{ secrets.CODECOV_TOKEN }}  # not required but might help API rate limits
